package no.nav.foreldrepenger.historikk.tjenester.tidslinje;

enum TidslinjeHendelseType {
    FØRSTEGANGSSØKNAD,
    FØRSTEGANGSSØKNAD_NY,
    ETTERSENDING,
    ENDRINGSSØKNAD,
    INNTEKTSMELDING,
    VEDTAK,
    VEDTAK_FØRSTEGANG,
    VEDTAK_ENDRING,
    VEDTAK_TILBAKEKREVING,
    VENTER_INNTEKTSMELDING,
    UTGÅENDE_INNHENT_OPPLYSNINGER,
    UTGÅENDE_ETTERLYS_INNTEKTSMELDING
}
