apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fpinfo-historikk
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50  
  liveness:
      path: api/actuator/info
      initialDelay: 60
  readiness:
      path: api/actuator/info
      initialDelay: 60  
  prometheus:
      enabled: true
      path: api/actuator/prometheus
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50
  resources:
      limits:
        cpu: 1500m
        memory: 3072Mi
      requests:
        cpu: 250m
        memory: 1536Mi 
  vault:
      enabled: true      
  env: 
   - name: no_nav_security_oidc_issuer_selvbetjening_discoveryurl
     value: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1 
   - name: spring_profiles_active
     value: dev42   
