apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fpinfo-historikk
  namespace: default
  labels:
    team: {{team}}
spec:
  image: https://cloud.docker.com/u/navikt/repository/docker/navikt:{{version}}
  port: 8080
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50  
  liveness:
      path: api/actuator/info
      initialDelay: 60
  readiness:
      path: api/actuator/info
      initialDelay: 60  
  prometheus:
      enabled: true
      path: api/actuator/prometheus
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50
  resources:
      limits:
        cpu: 1500m
        memory: 3072Mi
      requests:
        cpu: 250m
        memory: 1536Mi 
  vault:
      enabled: true      
  env:
   - name: kafka_username
     value: srvfpinfo-historikk  
   - name: spring_profiles_active
     value: preprod   
