management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

admin:
  username: vtp
  password: vtp
system:
  username: vtp
  password: vtp
server:
  port: 9003
vault:
  enabled: false
spring:
  cloud:
    vault:
      enabled: false
      database:
        role: fpinfohistorikk
        enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/fpinfohistorikk
    hikari:
      username: fpinfohistorikk
      password: fpinfohistorikk
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 2
    username: fpinfohistorikk
    password: fpinfohistorikk
  jpa:
    show-sql: false
    properties:
      hibernate: format_sql=true
    hibernate:
      ddl-auto: update

  flyway:
    baselineOnMigrate: true
    enabled: true
  mvc:
    log-request-details: true
  kafka:
    bootstrap-servers: localhost:9093
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${system.username} password=${system.password};
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            token-exchange:
              audience: local:teamforeldrepenger:fpsoknad-oppslag
            authentication:
              client-id: fpinfo-historikk
              client-jwk: src/test/resources/tokenx/jwk.json
          localhost:
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            token-exchange:
              audience: lokal
            authentication:
              client-id: fpinfo-historikk
              client-jwk: src/test/resources/tokenx/jwk.json
              client-auth-method: private_key_jwt
      issuer:
        tokenx:
          discovery-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
          accepted-audience: lokal

historikk:
  dittnav:
    enabled: true
  inntektsmelding:
    enabled: true
  oppslag:
    base-uri: http://localhost:9001/api
    enabled: true
  saf:
    base-uri: http://localhost:8060/rest/api/saf
    api-base-uri: http://localhost:9002/rest
    enabled: true
  innsending:
    søknad:
      enabled: true
      topic: fpsoknad-mottak-innsendinghendelse
  tilbakekreving:
    enabled: true
