management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

admin:
  username: vtp
  password: vtp
system:
  username: vtp
  password: vtp
server:
  port: 9003
vault:
  enabled: false
spring:
  cloud:
    vault:
      enabled: false
      database:
        role: fpinfohistorikk
        enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/fpinfohistorikk
    hikari:
      username: fpinfohistorikk
      password: fpinfohistorikk
    username: fpinfohistorikk
    password: fpinfohistorikk
  jpa:
    show-sql: false
    properties:
      hibernate: format_sql=true
    hibernate:
      ddl-auto: update
  flyway:
    baselineOnMigrate: true
    enabled: true
  mvc:
    log-request-details: true
kafka:
  onprem:
    bootstrap-servers: localhost:9092
    auto-offset-reset: earliest
  aiven:
    bootstrap-servers: localhost:9092

no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            token-exchange:
              audience: local:teamforeldrepenger:fpsoknad-oppslag
            authentication:
              client-id: fpinfo-historikk
              client-jwk: src/test/resources/tokenx/jwk.json
          localhost:
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            token-exchange:
              audience: lokal
            authentication:
              client-id: fpinfo-historikk
              client-jwk: src/test/resources/tokenx/jwk.json
              client-auth-method: private_key_jwt
      issuer:
        tokenx:
          discovery-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
          accepted-audience: lokal

historikk:
  dittnav:
    enabled: true
  inntektsmelding:
    enabled: false
  oppslag:
    enabled: false
  innsending:
    søknad:
      enabled: true
      topic: fpsoknad-mottak-innsendinghendelse
  tilbakekreving:
    enabled: false
