no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            token-exchange:
              audience: prod-fss:teamforeldrepenger:fpsoknad-mottak

vault:
  database-backend: postgresql/prod-fss
  database-role: fpinfo-historikk-prod-user
  database-admin-role: fpinfo-historikk-prod-admin
