management :
   endpoints.web.exposure.include:  '*'
   endpoint:
     health.show-details : always
     
spring.http.log-request-details : true
spring.datasource.url : postgresql://b27dbvl007.preprod.local:5432/fpinfo-historikk-preprod