no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            token-exchange:
              audience: prod-fss:teamforeldrepenger:fpsoknad-mottak
          safselvbetjening:
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            token-exchange:
              audience: prod-fss:teamdokumenthandtering:safselvbetjening
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt
historikk:
  saf:
    base-uri: https://safselvbetjening.intern.nav.no
    api-base-uri: https://foreldrepengesoknad-api.nav.no/rest

vault:
  database-backend: postgresql/prod-fss
  database-role: fpinfo-historikk-prod-user
  database-admin-role: fpinfo-historikk-prod-admin

spring:
  kafka:
    security:
      protocol: SSL
    ssl:
      trust-store-location: file:${kafka.truststore.path}
      trust-store-type: JKS
      trust-store-password: ${kafka.credstore.password}
      key-store-location: file:${kafka.keystore.path}
      key-store-type: PKCS12
      key-store-password: ${kafka.credstore.password}
    producer:
      properties:
        basic:
          auth:
            user:
              info: ${kafka.schema.registry.user}:${kafka.schema.registry.password}
            credentials:
              source: USER_INFO
        schema:
          registry:
            url: ${kafka.schema.registry}
