no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            token-exchange:
              audience: dev-fss:teamforeldrepenger:fpsoknad-mottak
          safselvbetjening-q1:
            token-exchange:
              audience: dev-fss:teamdokumenthandtering:safselvbetjening-q1
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt
historikk:
  dittnav:
    base-uri: https://foreldrepenger.dev.nav.no
  saf:
    base-uri: https://safselvbetjening-q1.dev.intern.nav.no
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
vault:
  database-backend: postgresql/preprod-fss
  database-role: fpinfo-historikk-preprod-user
  database-admin-role: fpinfo-historikk-preprod-admin
spring:
  datasource:
    url: jdbc:postgresql://b27dbvl007.preprod.local:5432/fpinfo-historikk-preprod
  jpa:
    open-in-view: false
  mvc:
    log-request-details: true
  kafka:
    security:
      protocol: SSL
    ssl:
      trust-store-location: file:${kafka.truststore.path}
      trust-store-type: JKS
      trust-store-password: ${kafka.credstore.password}
      key-store-location: file:${kafka.keystore.path}
      key-store-type: PKCS12
      key-store-password: ${kafka.credstore.password}
    producer:
      properties:
        basic:
          auth:
            user:
              info: ${kafka.schema.registry.user}:${kafka.schema.registry.password}
            credentials:
              source: USER_INFO
        schema:
          registry:
            url: ${kafka.schema.registry}
