no.nav:
  security:
    jwt:
      issuer:
        selvbetjening:
           discoveryUrl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
historikk:
   dittnav:
      enabled: true
      topics :
        beskjed: aapen-brukernotifikasjon-nyBeskjed-v1-testing
        oppgave:
           opprett: aapen-brukernotifikasjon-nyOppgave-v1-testing
           avslutt: aapen-brukernotifikasjon-done-v1-testing        
   sts:
      enabled: false  
   tilbakekreving:
      enabled: true
      topic: privat-tilbakekreving-brukerdialog-q1    
   vedtak:
      enabled: false
spring:
   datasource:
      url: jdbc:postgresql://b27dbvl007.preprod.local:5432/fpinfo-historikk-preprod
   http:
      log-request-details: true
   kafka:
      properties:
         schema:
           registry:
              url: https://kafka-schema-registry.nais-q.adeo.no
      consumer:
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
      producer:
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443