http:
   proxy: http://webproxy-nais.nav.no:8088
no.nav:
   security:         
      jwt.issuer.selvbetjening:
         discoveryurl: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
         cookie_name: selvbetjening-idtoken
         
historikk:
   dittnav:
      enabled: true
      topics :
        beskjed: aapen-brukernotifikasjon-nyBeskjed-v1
        oppgave: aapen-brukernotifikasjon-nyOppgave-v1
        done: aapen-brukernotifikasjon-done-v1   
   inntektsmelding:
      enabled: true
      topic: privat-foreldrepenger-brukerdialog-inntektsmelding   
   oppslag:
      uri: http://fpsoknad-oppslag.default.svc.nais.local/api
      enabled: true     
   innsending:
      søknad:
        enabled: true
        topic: fpsoknad-mottak
      fordeling:
        enabled: true
        topic: privat-foreldrepenger-historikk-fordeling
   tilbakekreving:
      enabled: true
      topic: privat-tilbakekreving-brukerdialog-p     
info:
   app:
      version: '@project.version@'
      build:
         time: '@timestamp@'
management:
   metrics:
      web:
         server:
            request:
              autotime:
                 enabled: true
   endpoint:
      health:    
         show-details : never            
   endpoints:
      web:
         exposure:
            include: info, health, metrics, prometheus
   health:
      refresh:
         enabled: false
      diskspace:
         enabled: false
server:
   servlet:
      context-path: /api
   forward-headers-strategy: framework
spring:
   application:
      name: fpinfo-historikk
   cache:
      cache-names: aktør,sts,organisasjon, fnr
      caffeine:
         spec: maximumSize=100,expireAfterAccess=3600s
   datasource:
      url: jdbc:postgresql://A01DBVL010.adeo.no:5432/fpinfo-historikk-prod
      hikari:
         connection-test-query: SELECT 1
         maximum-pool-size: 2
   flyway:
      baselineOnMigrate: false
      enabled: true
   jackson:
      default-property-inclusion: non-absent
      mapper:
         accept-case-insensitive-properties: true
      deserialization:
         accept-single-value-as-array: true
         fail-on-unknown-properties: true
      serialization:
         write-empty-json-arrays: false
         fail-on-empty-beans: false
   jpa:
      hibernate:
         ddl-auto: none
   kafka:
      properties:
         schema:
           registry:
             url:   https://kafka-schema-registry.nais.adeo.no
         security:
            protocol: SASL_SSL
         sasl:
            mechanism: PLAIN
            jaas:
               config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${system.username} password=${system.password};
      consumer:
         enable-auto-commit: false
         bootstrap-servers: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443
         group-id: group_id
         auto-offset-reset: earliest
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      producer:
         bootstrap-servers: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443
         key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
         value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer 
         transaction-id-prefix: tx.
   main:
      banner-mode: 'off'