no.nav.security.jwt.issuer.selvbetjening.discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
dokarkiv:
   enabled: false
   service: https://dokarkiv-q1.nais.preprod.local

aktoer:
  base-uri: https://app-q1.adeo.no/aktoerregister/api
management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
historikk:
  vedtak:
     enabled: true
  dittnav:
      enabled: true
  kafka:
      topics:
         beskjed: aapen-brukernotifikasjon-nyBeskjed-v1-testing
         oppgave:
            opprett: aapen-brukernotifikasjon-nyOppgave-v1-testing
            done: aapen-brukernotifikasjon-done-v1-testing
         søknad: fpsoknad-mottak
         inntektsmelding: privat-foreldrepenger-brukerdialog-inntektsmelding
         tilbakekreving: privat-tilbakekreving-brukerdialog-q1
spring:
   datasource:
      url: jdbc:postgresql://b27dbvl007.preprod.local:5432/fpinfo-historikk-preprod
   http:
      log-request-details: true
   kafka:
      properties:
         schema.registry.url: https://kafka-schema-registry.nais-q.adeo.no/
      consumer:
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
      producer:
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
         key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
         value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer