http:
   proxy: http://webproxy-nais.nav.no:8088
no.nav:
   security:         
      jwt.issuer.selvbetjening:
         discoveryurl: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
         cookie_name: selvbetjening-idtoken
dokarkiv:
   enabled: false
   service: https://dokarkiv
sts:
  enabled: true           
historikk:
   vedtak:
     enabled: false
   dittnav:
      enabled: false
   inntektsmelding:
      enabled: true
   oppslag:
      enabled: true
   kafka:
      topics:
         vedtak: privat-familie-vedtakFattet-v1
         beskjed: aapen-brukernotifikasjon-nyBeskjed-v1
         tilbakekreving: privat-tilbakekreving-brukerdialog-p
         oppgave:
            opprett: aapen-brukernotifikasjon-nyOppgave-v1
            done: aapen-brukernotifikasjon-done-v1
         søknad: fpsoknad-mottak
         inntektsmelding: privat-foreldrepenger-brukerdialog-inntektsmelding
info:
   app:
      version: '@project.version@'
      build:
         time: '@timestamp@'
management:
   metrics:
      web:
         server:
            auto-time-requests: true
   endpoint:
      health:    
         show-details : never            
   endpoints:
      web:
         exposure:
            include: info, health, metrics, prometheus
   health:
      refresh:
         enabled: false
      diskspace:
         enabled: false
server:
   servlet:
      context-path: /api
   use-forward-headers: true
spring:
   application:
      name: fpinfo-historikk
   cache:
      cache-names: aktør,sts,organisasjon, fnr
      caffeine:
         spec: maximumSize=100,expireAfterAccess=3600s
   datasource:
      url: jdbc:postgresql://A01DBVL010.adeo.no:5432/fpinfo-historikk-prod
      hikari:
         connection-test-query: SELECT 1
         maximum-pool-size: 2
   flyway:
      baselineOnMigrate: false
      enabled: true
   jackson:
      default-property-inclusion: non-absent
      mapper:
         accept-case-insensitive-properties: true
      deserialization:
         accept-single-value-as-array: true
         fail-on-unknown-properties: true
      serialization:
         write-empty-json-arrays: false
         fail-on-empty-beans: false
   jpa:
      hibernate:
         ddl-auto: none
   kafka:
      properties:
         security:
            protocol: SASL_SSL
         sasl:
            mechanism: PLAIN
            jaas:
               config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka.username} password=${kafka.password};
      consumer:
         enable-auto-commit: false
         bootstrap-servers: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443
         group-id: group_id
         auto-offset-reset: earliest
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      producer:
         bootstrap-servers: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.apache.kafka.common.serialization.StringSerializer
         transaction-id-prefix: tx.
   main:
      banner-mode: 'off'