no.nav:
    security:
        jwt:
          client:
             registration:
                 fpsoknad-mottak:
                     token-exchange:
                         audience: dev-fss:teamforeldrepenger:fpsoknad-mottak
management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
historikk:
   dittnav:
      enabled: true
   tilbakekreving:
      enabled: true
      topic: privat-tilbakekreving-brukerdialog-q1
spring:
   config.import: vault://
   cloud:
      vault:
         enabled: true
         uri: https://vault.adeo.no
         database:
            enabled: true
            role: fpinfo-historikk-preprod-admin
            backend: postgresql/preprod-fss
         authentication: KUBERNETES
         kubernetes:
            role: fpinfo-historikk
            kubernetes-path: kubernetes/preprod/fss
            service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
         kv:
            enabled: true
            backend: kv/preprod/fss
            application-name: fpinfo-historikk/teamforeldrepenger
            default-context: fpinfo-historikk/teamforeldrepenger
   datasource:
      url: jdbc:postgresql://b27dbvl007.preprod.local:5432/fpinfo-historikk-preprod
   mvc:
      log-request-details: true
   kafka:
      properties:
         schema:
           registry:
              url: https://kafka-schema-registry.nais-q.adeo.no
      consumer:
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
      producer:
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
