management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

admin:
  username: ${systembruker.username}
  password: ${systembruker.password}
server:
  port: 9003
vault:
  enabled: false
spring:
  cloud:
    vault:
      enabled: false
    database:
      role: ${defaultds.username}
      enabled: false
  datasource:
    url: ${defaultds.url}
    hikari:
      username: ${defaultds.username}
      password: ${defaultds.password}
    username: ${defaultds.username}
    password: ${defaultds.username}
  jpa:
    show-sql: false
    properties:
      hibernate: format_sql=true
    hibernate:
      ddl-auto: update
  flyway:
    baselineOnMigrate: true
    enabled: true
  mvc:
    log-request-details: true
  kafka:
    bootstrap-servers: ${kafka.brokers}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${systembruker.username} password=${systembruker.password};
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

kafka:
  onprem:
    jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${systembruker.username} password=${systembruker.password};
    bootstrap-servers: ${kafka.brokers}
    auto-offset-reset: earliest

no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            token-exchange:
              audience: lokal
          saf: # TODO: legg inn i application.yml
            token-exchange:
              audience: lokal
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt

historikk:
  dittnav:
    enabled: false
  inntektsmelding:
    enabled: false
  oppslag:
    base-uri: ${fpsoknad-mottak.override.url}
  innsending:
    søknad:
      enabled: true
      topic: ${kafka.innsendinghendelse.topic}
  tilbakekreving:
    enabled: false
  saf:
    base-uri: http://vtp:8060/rest/api/saf
    enabled: true
