no.nav:
    security:
        jwt:
          client:
             registration:
                 fpsoknad-mottak:
                     token-exchange:
                         audience: dev-fss:teamforeldrepenger:fpsoknad-mottak
management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
historikk:
   dittnav:
      enabled: true       
   tilbakekreving:
      enabled: true
      topic: privat-tilbakekreving-brukerdialog-q1    
spring:
   datasource:
      url: jdbc:postgresql://b27dbvl007.preprod.local:5432/fpinfo-historikk-preprod
   mvc:
      log-request-details: true
   kafka:
      properties:
         schema:
           registry:
              url: https://kafka-schema-registry.nais-q.adeo.no
      consumer:
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
      producer:
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443