no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            token-exchange:
              audience: prod-fss:teamforeldrepenger:fpsoknad-mottak

vault:
  database-backend: postgresql/prod-fss
  database-role: fpinfo-historikk-prod-user
  database-admin-role: fpinfo-historikk-prod-admin

spring:
  kafka:
    security:
      protocol: SSL
    ssl:
      trust-store-location: file:${kafka.truststore.path}
      trust-store-type: JKS
      trust-store-password: ${kafka.credstore.password}
      key-store-location: file:${kafka.keystore.path}
      key-store-type: PKCS12
      key-store-password: ${kafka.credstore.password}
