dokarkiv:
   service: https://dokarkiv-q1.nais.preprod.local

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always   

spring:
   datasource:
      url: jdbc:postgresql://b27dbvl007.preprod.local:5432/fpinfo-historikk-preprod
   http:
      log-request-details: true
   kafka:
      consumer:
         enable-auto-commit: false
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
         group-id: group_id
         auto-offset-reset: earliest
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      producer:
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.apache.kafka.common.serialization.StringSerializer
         transaction-id-prefix: tx.