import.enabled : true
import.name : /Users/jan-olaveide/EclipseWS/fpinfo-historikk/src/test/resources/im
management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
sts:
   enabled: false
historikk:
   inntektsmelding:
      enabled: true
   oppslag:
      enabled: false
   kafka:
      meldinger:
         topic: privat-tilbakekreving-brukerdialog-local      
dokarkiv:
   enabled: false
server:
   port: 9000    
spring:
   application:
      admin:
         enabled: true
   datasource:
      hikari:
        connection-test-query: SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS
      url: jdbc:hsqldb:mem:testdb      
   jpa:
      show-sql: false
      properties:
         hibernate: format_sql=true
      hibernate:
         ddl-auto: update
   flyway:
      enabled: false
   http:
      log-request-details: false
   kafka:
      properties:
         security:
            protocol: PLAINTEXT 
      consumer:
         bootstrap-servers: localhost:9092
      producer:
         bootstrap-servers: localhost:9092