no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            token-exchange:
              audience: prod-fss:teamforeldrepenger:fpsoknad-mottak

spring:
  cloud:
    vault:
      database:
        role: fpinfo-historikk-prod-admin
        backend: postgresql/prod-fss
      kubernetes:
        kubernetes-path: kubernetes/prod/fss
      kv:
        backend: kv/prod/fss
