no.nav:
  security:
    jwt:
      dont-propagate-bearertoken: false
      client:
        registration:
          fpsoknad-mottak:
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt
      issuer:
        tokenx:
          discovery-url: ${token.x.well.known.url}
          accepted-audience: ${token.x.client.id}

historikk:
  dittnav:
    enabled: true
    topics:
      beskjed: min-side.aapen-brukernotifikasjon-beskjed-v1
      oppgave: min-side.aapen-brukernotifikasjon-oppgave-v1
      done: min-side.aapen-brukernotifikasjon-done-v1
  inntektsmelding:
    enabled: true
    topic: teamforeldrepenger.inntektsmelding-innsendinghendelse-v1
    group-id: fpinfo-historikk-inntektsmelding
  innsending:
    søknad:
      enabled: true
      topic: teamforeldrepenger.selvbetjening-innsendinghendelse-v1
      group-id: fpinfo-historikk-innsending
  tilbakekreving:
    enabled: true
    topic: teamforeldrepenger.tilbakekreving-brukerdialog-v1
    group-id: fpinfo-historikk-tilbakekreving

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  health:
    refresh:
      enabled: false
    diskspace:
      enabled: false
  endpoint:
    health:
      group:
        liveness:
          include: db
      show-details: never
server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework
vault:
  enabled: true
spring:
  application:
    name: fpinfo-historikk
  cache:
    cache-names: aktør,organisasjon
    caffeine:
      spec: maximumSize=100,expireAfterAccess=3600s
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: false
  datasource:
    url: jdbc:postgresql://A01DBVL010.adeo.no:5432/fpinfo-historikk-prod
  flyway:
    baselineOnMigrate: false
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  main:
    banner-mode: 'off'
  kafka:
    bootstrap-servers: ${kafka.brokers}
    consumer:
      properties:
        isolation.level: read_committed
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      client-id: fpinfo-historikk
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

springdoc:
  packages-to-scan: no.nav.foreldrepenger.historikk
  paths-to-match: /**/
  show-actuator: false
