
http.proxy : http://webproxy-nais.nav.no:8088

info.app :
    version : '@project.version@'
    build.time : '@timestamp@'

management:
    metrics.web.server.auto-time-requests : true
    endpoints.web.exposure.include:  info, health, metrics, prometheus
    health :
      diskspace.enabled: false
      jms.enabled: false
      
server :
    servlet.context-path :  /api
    use-forward-headers: true
spring:
   jpa.hibernate.ddl-auto : none
   flyway:
      baselineOnMigrate : true
      enabled : true    
   application.name : fpinfo-historikk
   jackson :
       default-property-inclusion :  non-absent
       mapper :
         accept-case-insensitive-properties: true
       deserialization :
         accept-single-value-as-array: true
         fail-on-unknown-properties: true
       serialization :
         write-empty-json-arrays: false
         fail-on-empty-beans: false
   main.banner-mode : 'off'
   
kafka.topic : fpinfo-historikk
 