no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            token-exchange:
              audience: dev-fss:teamforeldrepenger:fpsoknad-mottak
historikk:
  dittnav:
    base-uri: https://foreldrepenger.dev.nav.no
  tilbakekreving:
    topic: privat-tilbakekreving-brukerdialog-q1
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  config:
    import: vault://
  cloud:
    vault:
      enabled: true
      uri: https://vault.adeo.no
      authentication: KUBERNETES
      database:
        enabled: true
        role: fpinfo-historikk-preprod-admin
        backend: postgresql/preprod-fss
      kubernetes:
        role: fpinfo-historikk
        kubernetes-path: kubernetes/preprod/fss
      kv:
        enabled: true
        backend: kv/preprod/fss
        application-name: fpinfo-historikk/teamforeldrepenger
        default-context: fpinfo-historikk/teamforeldrepenger
  datasource:
    url: jdbc:postgresql://b27dbvl007.preprod.local:5432/fpinfo-historikk-preprod
  mvc:
    log-request-details: true
kafka:
  onprem:
    bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
