management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
sts:
   enabled: false
historikk:
   oppslag:
      enabled: false
dokarkiv:
   enabled: false
spring:
   application:
      admin:
         enabled: true
   datasource:
      url: jdbc:hsqldb:mem:testdb      
   jpa:
      show-sql: false
      properties:
         hibernate: format_sql=true
      hibernate:
         ddl-auto: update
   flyway:
      enabled: false
   http:
      log-request-details: false
   kafka:
      properties:
         security:
            protocol: PLAINTEXT 
      consumer:
         bootstrap-servers: localhost:9092
      producer:
         bootstrap-servers: localhost:9092