spring:
   config.import: vault://
   cloud:
      vault:
         enabled: true
         uri: https://vault.adeo.no
         database:
            enabled: true
            role: fpinfo-historikk-prod-admin
            backend: postgresql/prod-fss
         authentication: KUBERNETES
         kubernetes:
            role: fpinfo-historikk
            kubernetes-path: kubernetes/prod/fss
            service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
         kv:
            enabled: true
            backend: kv/prod/fss
            application-name: fpinfo-historikk/teamforeldrepenger
            default-context: fpinfo-historikk/teamforeldrepenger
