version: 2
jobs:
   build:
     working_directory: ~/fpinfo-historikk 
     docker:
       - image: circleci/openjdk:8u171-jdk
     steps:
       - checkout
       - restore_cache: 
          key: fpinfo-historikk-{{ checksum "pom.xml" }}
      
       - run: mvn dependency:go-offline
      
       - save_cache:
          paths:
            - ~/.m2
          key: fpinfo-historikk-{{ checksum "pom.xml" }}
       - run: mvn test 
       - store_test_results: 
          path: target/surefire-reports
