version: 2
orbs:
  nais: navikt/nais-deployment:1.1.1
  workflow:
  deploy-docker-and-nais:
    jobs:
      - nais/deploy:
          context: NAIS deployment
          repo: navikt/fpinfo-historikk
          image: navikt/fpinfo-historikk
          github-app-id: 20250
          nais-template: nais.yaml
          environment: dev-fss
          team: teamforeldrepenger
jobs:
   build:
     working_directory: ~/fpinfo-historikk 
     docker:
       - image: circleci/openjdk:8u171-jdk
     steps:
       - checkout
       - restore_cache: 
          key: fpinfo-historikk-{{ checksum "pom.xml" }}
      
       - run: mvn dependency:go-offline
      
       - save_cache:
          paths:
            - ~/.m2
          key: fpinfo-historikk-{{ checksum "pom.xml" }}
       - run: mvn test 
       - run:
           name: Save test results
           command: |
             mkdir -p ~/test-results/junit/
             find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
           when: always

       - store_test_results:
          path: ~/test-results

       - store_artifacts:
          path: ~/test-results/junit 
       - deploy-docker-and-nais   
          
