version: 2.1
orbs:
  nais: navikt/nais-deployment@1.1.0
  
jobs:
   build:
     working_directory: ~/fpinfo-historikk 
     docker:
       - image: circleci/openjdk:8u171-jdk
     steps:
       - checkout       
       - restore_cache: 
          key: fpinfo-historikk-{{ checksum "pom.xml" }}
      
       - run: mvn dependency:go-offline
      
       - save_cache:
          paths:
            - ~/.m2
          key: fpinfo-historikk-{{ checksum "pom.xml" }}
       - run: mvn package 
       - run:
           name: Save test results
           command: |
             mkdir -p ~/test-results/junit/
             find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
           when: always

       - store_test_results:
          path: ~/test-results

       - store_artifacts:
          path: ~/test-results/junit  
          
       - nais/docker-deploy:
          image: navikt/fpinfo-historikk
workflows:
   version: 2
   deploy-nais:
     jobs:
      - build:
          context: NAIS deployment
      - nais/deploy:
          build-and-push-docker-image: false
          context: NAIS deployment
          repo: navikt/fpinfo-historikk
          image: navikt/fpinfo-historikk
          github-app-id: 20250
          nais-template: naiserator.yaml
          environment: dev-fss
          team: teamforeldrepenger
          requires:
            - build
