apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fpinfo-historikk
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: foreldrepengesoknad-api
          namespace: teamforeldrepenger
          cluster: {{cluster_foreldrepengesoknad-api}}
  kafka:
    pool: {{kafkaPool}}
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: api/actuator/health/liveness
    initialDelay: 60
  readiness:
    path: api/actuator/health/readiness
    initialDelay: 60
  prometheus:
    enabled: true
    path: api/actuator/prometheus
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  vault:
    enabled: true
  env:
    {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
    {{/each}}
  resources:
      limits:
        cpu: 1500m
        memory: 3072Mi
      requests:
        cpu: 50m
        memory: 1024Mi
  secureLogs:
    enabled: true
