ALTER TABLE DITTNAVOPPGAVER ADD EKSTERN_REFERANSE_ID VARCHAR(37);
ALTER TABLE DITTNAVOPPGAVER ADD INTERN_REFERANSE_ID VARCHAR(36);
ALTER TABLE DITTNAVOPPGAVER ADD GRUPPERINGS_ID VARCHAR(36);
ALTER TABLE DITTNAVOPPGAVER ADD SENDT_DONE BOOLEAN DEFAULT FALSE;
