ALTER TABLE DITTNAVOPPGAVER ADD EKSTERN_REFERANSE_ID VARCHAR(50);
ALTER TABLE DITTNAVOPPGAVER ADD INTERN_REFERANSE_ID VARCHAR(50);
ALTER TABLE DITTNAVOPPGAVER ADD GRUPPERINGS_ID VARCHAR(50);
ALTER TABLE DITTNAVOPPGAVER ADD SENDT_DONE BOOLEAN DEFAULT FALSE;
ALTER TABLE DITTNAVOPPGAVER ADD TYPE VARCHAR(50);
