name: Build PR or branch

on:
    pull_request:
        branches:
            - master

jobs:
    kompiler:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Sett opp Java 15
              uses: actions/setup-java@v2
              with:
                  java-version: 15
                  distribution: 'adopt'
                  cache: 'maven'

            - name: Kompiler
              run: |
                mvn jacoco:prepare-agent verify jacoco:report sonar:sonar -e --batch-mode --settings .github/.m2/settings.xml -Dsonar.login=${SONAR_TOKEN}
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Hvis repo blir avhengig av private biblioteker trengs en PAT.
