name: Slash command dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:      
      - name: Slash command dispatch
        uses: peterevans/slash-command-dispatch@v1
        with:
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.NOTIFICATION }}
          commands: promote
          issue-type: issue 
          allow_edits: true   
          reactions: false     
